# Error raising class
class DimensionalityException(Exception):
    pass

# Function for computing Euclidean distance
def distance (a,b):
    """
    This function takes two lists of float type that are of equal length as its arguments. 
    The function returns the Euclidean distance between the two lists, considered as vectors 
    in a space of dimensionality equal to the length of the lists. That is to say, computes 
    the element-by-element difference between the two lists, squares that, sum all the squares 
    and takes a square root of the final sum. The function raises an error if the two lists passed 
    are not of the same length, or if they are both empty.
    """

    #Accounting for unequal input list elements
    if len(a) != len(b):
        raise DimensionalityException("Lists lengths are not equal")

    #Accounting for empty input lists
    if a == [] and b == []:
        raise DimensionalityException("Lists are empty")


    #Calculate difference between each element of lists
    difference = []
    for i, j in zip(a, b):
        x = (i-j)
        difference.append(x)
    
    #Calculate squares
    square = []
    for i in difference:
        x = i**2
        square.append(x)

    #Calculate square root of the sum of squares
    answer = (sum(square))**0.5
    answer = float("%.2f" % answer)
    return(answer)

# Function for reading data in tabular format
def readTable (filename):
    """
    This function takes a string called 'filename' as its argument. The function reads a TSV table 
    formatted file generated by the AAtypetable function previously. The function returns a dictionary 
    with the filenames as its keys; the value associated to each key is a list of floats, containing 
    in order the percentages of polar, small and hydrophobic AAs, as listed in the table. 
    """

    #Import file for writing
    INFILE=open(filename,"r")
    INFILE.readline() # skip header
    
    #Build lists of each column
    name = []
    polar = []
    small = []
    hydro = []
    for line in INFILE:
        list_split = line.split('\t')
        x = str (list_split[0])
        name.append(x)
        x = float (list_split[1])
        polar.append(x)
        x = float (list_split[2])
        small.append(x)
        x = float (list_split[3])
        hydro.append(x)
    
    #List together polar, small, hydro residues for each file
    sorted = []
    length = len(polar)  
    for i in range(length):
        x = [polar[i], small[i], hydro[i]]
        sorted.append(x)
    
    #Correspond file names to sorted list
    dict = {}
    for name, sorted in zip(name, sorted): 
        dict[name] = sorted
    
    #Close file
    INFILE.close()
    
    #Return dictionary
    return(dict)

# Function for computing distance matrix
def distanceMatrix (inputfile, outputfile):
    """
    This function takes as its argument two strings called 'inputfile' and 'outputfile', 
    used to pass the names of the input and output file. The functions read from 
    the input file a TSV table created previously. Suppose data for N proteins are read.
    The function then creates an output TSV file containing a matrix of size NxN 
    (plus one row and one column for labels). The rows and columns of the matrix correspond 
    to individual protein file names, so that each matrix entry corresponds to a pair of proteins. 
    The matrix contains the distance between the '[polar, small, hydro]' lists (considered as 3 
    dimensional vectors) corresponding to a pair of proteins.
    """

    #Import TSV file
    tsv_file = readTable(inputfile)

    #Extract and list percentage values from dictionary 
    percentages = list(tsv_file.values())

    #Obtain number of elements in list
    number_of_elements = len(percentages)
   
    #Calculator distances for each element of the list against each other
    distances = []
    for j in range(0,number_of_elements):
        for i in range(0,number_of_elements):
            x = distance(percentages[j],percentages[i])
            distances.append(x)
    
    #Sublist distances for each row in the matrix
    distances = [distances[i:i+number_of_elements] for i in range(0, len(distances), number_of_elements)]

    #Extract file names from dictionary
    names = tsv_file.keys()
    names = list(names)

    #Listing file names and corresponding distances
    zipped_list = []
    for i, j in zip(names, distances):
        x = str(i) + str(j)
        zipped_list.append(x)

    #Writing output file
    OUTF = open (outputfile, "w")
    OUTF.write("# " + outputfile + "\t")
    for i in names:
        header_row = i + '\t'
        OUTF.write(header_row)
    OUTF.write('\n')
    for i in range (0,number_of_elements):
        replaced = zipped_list[i].replace(",","\t")
        replaced = replaced.replace("[","\t")
        replaced = replaced.replace("]","\n")   
        OUTF.write(replaced)   
    OUTF.close()